[package]
name = "OptionsAnalysisToolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
statrs = "0.15.0"
rand = "0.8.5"
rand_distr = "0.4"  # or the latest version
yew = { version = "0.21", features = ["csr"] }